### ISSUE TITLE
Support keyboard shortcut for firefox

### ISSUE THREAD

**Issue by azzamsa** [chitsaou/copy-as-markdown#57] opened 2018-03-25 02:02 UTC
I use this extension dozen times a day. I saw in README that keybinding/shortcut only works in chrome.

Can we hope *adding shortcut support for Firefox* ?

Many keyboard binding extension stop working for Quantum. But I find [saka](https://addons.mozilla.org/en-US/firefox/addon/saka-key/) works in Quantum. So I think there is still a hope :).

**Comment by chitsaou** [comment] 2018-04-07 06:04
Thanks for the idea.

In fact we can set shortcut for add-on commands, but the problem is that Firefox does not have a native UI to change the shortcut. So even if there is the shortcut, as a user you don't know it exists.

The current possible way to set it is to make an options page for the add-on.

https://bugzilla.mozilla.org/show_bug.cgi?id=1421811

https://github.com/mdn/webextensions-examples/tree/master/commands

I'll see if there is a way to share these two features between Chrome and Firefox.

Thanks!

**Comment by rnuske** [comment] 2018-08-15 15:06
Thanks a lot. A shortcut for  'Current tab link' in Firefox would be awesome. It's the last thing why I need to touch the mouse while writing Markdown documents.

**Comment by aiman** [comment] 2019-07-02 14:18
FYI Firefox 66+ now supports extension shortcut keys!

**Comment by chitsaou** [comment] 2019-10-26 03:09
Closing because it's supported by Firefox officially!

**Closed by chitsaou** 2019-10-26 03:09 UTC
Labels: feature, firefox
