### ISSUE TITLE
Make list style configurable

### ISSUE THREAD

**Issue by mootari** [chitsaou/copy-as-markdown#68] opened 2019-06-09 11:34 UTC
Currently the list style used to export links is [hardcoded to asterisks](https://github.com/chitsaou/copy-as-markdown/blob/7c764a9deef190d48763a245370851a4c8c5dbd2/src/background/lib/markdown.js#L44). I'd love to see an option to change the style:
- asterisk (i.e. "* ...", "* ...")
- dash (i.e. "- ...", "- ...")
- numbered list (i.e. "1. ...", "1. ...")

**Comment by chitsaou** [comment] 2019-10-14 06:27
Hi, thanks for your suggestion. This is a duplicate of #12 so I'd like to close this issue.

That said, I've did some refactoring and found that it might be easier to implement this feature.

**Closed by chitsaou** 2019-10-14 06:27 UTC
